### ISSUE TITLE
could not create deployments

### ISSUE THREAD

**Issue by Pamir** [henrybell/advanced-kubernetes-bootcamp#44]
Hi,
The command below creates 3 kubernetes clusters and does not create necessary pods and deployments like istio prometheus spinnaker
_gcloud deployment-manager deployments create --config workshop.yaml adv-bc-$(date +%s)_ 

Also i deleted all service accounts associated with dm's deployment. Are there any additional tasks to do? When you delete service accounts  only prometheus is deployed. Could you please assist me to re create the lab environment in the same project.

regards.

**Comment by henrybell** [comment]
It's difficult to debug remotely without more detail but it is possible you are hitting a CPU quota limit that is preventing the deployment from completing successfully. Please increase the CPU quota in the us-central1 region and try again.

If you plan on completing the lab modules, you'll find that the lab content in this repository is currently inconsistent with what is deployed, with different regions in use and so on. This is because the labs have now been imported into the [Qwiklabs](https://google.qwiklabs.com) environment (from where this training course is designed to be run), and modified in-place. I plan to merge these changes back in to this repo, but can't give an estimate on when this will be complete.

**Comment by Pamir** [comment]
Hi @henrybell 
I tried to figure out but the case is not related with Quotas. I deleted all the vms and checked the Quotas and tried to complete the initial setup for several times. Thank you very much for your quick response. I will debug it and inform you.

regards

**Comment by Pamir** [comment]
Hi @henrybell  
In newly created projects it is working like a charm. On the other hand, you have to delete everthing. Instead of deleting service accounts / clusters  vms ..etc, creating a fresh project is ok.
